const ENG=[
{name:'高等数学（一）',icon:'∑',desc:'函数、极限、导数、微分与积分。',pct:68,score:86,units:4},
{name:'大学英语（一）',icon:'EN',desc:'词汇、阅读、写作与阶段测试。',pct:54,score:82,units:4},
{name:'人工智能概论',icon:'AI',desc:'人工智能基础、机器学习、大模型认知。',pct:72,score:91,units:3},
{name:'思想道德与法治',icon:'◎',desc:'章节学习、知识梳理与课程测试。',pct:61,score:88,units:4},
{name:'大学语文',icon:'文',desc:'阅读、表达、名著与课程作业。',pct:63,score:85,units:3},
{name:'军事理论',icon:'◇',desc:'课程阅读、知识点与阶段测评。',pct:45,score:84,units:3},
{name:'劳动教育',icon:'劳',desc:'实践记录与课程完成情况。',pct:40,score:90,units:2}
];
const CS=[
{name:'Python 程序设计',icon:'Py',desc:'语法 → 函数 → 文件 → OOP → 项目。',pct:35,score:78,status:'进行中',units:5},
{name:'C 语言基础',icon:'C',desc:'变量、数组、指针、结构体与文件。',pct:8,score:0,status:'下一阶段',units:5},
{name:'数据结构',icon:'DS',desc:'数组、链表、栈、队列、树、排序。',pct:0,score:0,status:'待开始',units:6},
{name:'数据库 / MySQL',icon:'DB',desc:'SQL、表设计、查询、CRUD与项目实践。',pct:0,score:0,status:'待开始',units:5},
{name:'Web 开发',icon:'Web',desc:'HTML、CSS、JavaScript与全栈基础。',pct:0,score:0,status:'待开始',units:5},
{name:'AI 应用开发',icon:'AI',desc:'API、RAG、学习助手与创业项目。',pct:0,score:0,status:'后置',units:4}
];
const CONTENT={
'Python 程序设计':{chapters:[
['1 变量与数据类型','掌握变量赋值、数字、字符串、布尔值，以及基本输入输出。',['变量赋值：name = "Alex"','常见类型：int / float / str / bool','input() 获取输入，print() 输出结果'],['写一个成绩判断程序：输入0~100分数，输出优秀/良好/及格/不及格。']],
['2 条件与循环','掌握 if/elif/else、for、while 与循环控制。',['条件分支用于选择执行路径','for 适合遍历序列，while 适合条件循环','break / continue 控制循环过程'],['统计1~100中偶数的和，并输出结果。']],
['3 函数','掌握函数定义、参数、返回值与作用域。',['def 创建函数','return 返回结果','参数让程序更可复用'],['编写 calculate_average(scores) 返回平均分。']],
['4 文件与异常','掌握文本文件读写和基础异常处理。',['open() / read() / write()','with 自动管理文件','try/except 捕获常见异常'],['读取一个成绩文件并统计平均分。']],
['5 面向对象与项目','理解类、对象、方法，并完成小项目。',['class 定义类','对象保存状态','方法封装行为'],['完成一个简易学生信息管理程序。']]
]}
};
const QUIZ=[{id:1,q:'Python中正确的变量赋值方式是？',a:['A. int a','B. define a','C. score = 90','D. var score'],ok:2,why:'Python 使用“变量名 = 值”的形式赋值。'},{id:2,q:'以下哪个是布尔值？',a:['A. True','B. "True"','C. 1','D. 0'],ok:0,why:'True/False 是 Python 的布尔值。'},{id:3,q:'下列哪个关键字用于返回函数结果？',a:['A. out','B. return','C. back','D. yield'],ok:1,why:'return 将值返回给调用者。'}];
const baseTasks=[{id:'math',name:'高等数学（一）· 极限复习 30 分钟',sub:'工程管理'},{id:'py',name:'Python · 当前章节练习 60 分钟',sub:'计算机主线'},{id:'eng',name:'大学英语 · 四级词汇 30 个',sub:'工程管理'},{id:'start',name:'创业 · 访谈 1 名同学',sub:'创业实践'}];
const state={tasks:JSON.parse(localStorage.getItem('g7_tasks')||'null')||baseTasks.map(x=>({...x,done:false})),logs:JSON.parse(localStorage.getItem('g7_logs')||'[]'),wrong:JSON.parse(localStorage.getItem('g7_wrong')||'[]'),projects:JSON.parse(localStorage.getItem('g7_projects')||'null')||[{id:1,name:'访谈 3 名同学',done:false},{id:2,name:'完成学习助手原型',done:false},{id:3,name:'整理用户反馈',done:false}]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('g7_tasks',JSON.stringify(state.tasks));localStorage.setItem('g7_logs',JSON.stringify(state.logs));localStorage.setItem('g7_wrong',JSON.stringify(state.wrong));localStorage.setItem('g7_projects',JSON.stringify(state.projects));}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={home:'今天，也为转专业多走一步。',today:'把今天的任务做完，再谈下一步。',eng:'先把工程管理的成绩守住。',cs:'从零补齐计算机基础能力。',courses:'学懂、练会、再测试。',tests:'学完就测，测完才解锁。',wrong:'错题不是终点，是下一轮入口。',grades:'看见真实进步，也看见薄弱环节。',startup:'小步验证，把创业做成项目。',ai:'让数据驱动你的下一周。'};$('#pageTitle').textContent=titles[page];window.scrollTo({top:0,behavior:'smooth'});}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page)); $$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));
$('#theme').onclick=()=>document.body.classList.toggle('soft');
function taskHTML(){return state.tasks.map(t=>`<div class="task ${t.done?'done':''}"><button class="check" onclick="toggleTask('${t.id}')"></button><div><b>${t.name}</b><small>${t.sub}</small></div></div>`).join('')}
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);t.done=!t.done;save();render();}; $('#reset').onclick=()=>{state.tasks.forEach(x=>x.done=false);save();render();};
function renderTasks(){$('#tasks').innerHTML=taskHTML();$('#homeTasks').innerHTML=taskHTML();let done=state.tasks.filter(x=>x.done).length;$('#rate').textContent=Math.round(done/state.tasks.length*100)+'%';}
function renderCourses(arr,el,cs=false){$(el).innerHTML=arr.map((c,i)=>`<div class="courseCard ${c.pct===0&&cs?'locked':''}"><div class="courseIcon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p><div class="meta"><span>${cs?c.status:c.units+' 个学习单元'}</span><span>${c.pct}% ${c.score?`· ${c.score}分`:''}</span></div><div class="track"><i style="width:${c.pct}%"></i></div><button class="mini" onclick="openCourse('${c.name}')">${c.pct?'继续学习':'查看课程'}</button></div>`).join('')}
function openCourse(name){const data=CONTENT[name]||{chapters:[['课程简介','这门课程将围绕核心知识点、作业和测试推进。',['先学习知识点','完成课后任务','参加章节测试'],['写下本章总结，并完成自测。']]]};const view=$('#courseView');view.className='courseView panel';view.innerHTML=`<div class="lessonHead"><div><small class="eyebrow">NOW LEARNING</small><h3>${name}</h3></div><button class="ghost" onclick="go('courses')">返回</button></div><div class="lessonTabs">${data.chapters.map((c,i)=>`<button class="${i===0?'active':''}" onclick="showLesson('${name}',${i})">${c[0]}</button>`).join('')}</div><div id="lessonContent"></div>`;showLesson(name,0);go('courses');}
window.openCourse=openCourse;window.showLesson=(name,i)=>{const data=CONTENT[name];const c=(data||{chapters:[['简介','课程内容准备中。',[],['完成一项练习。']]]}).chapters[i];$('#lessonContent').innerHTML=`<div class="lessonBox"><h4>${c[0]}</h4><p>${c[1]}</p><h4>知识点</h4><ul>${c[2].map(x=>`<li>${x}</li>`).join('')}</ul><h4>课后作业</h4><p>${c[3][0]}</p><button class="primary" onclick="startQuiz('${name}',${i})">完成学习，进入本章测试</button></div>`};
function renderLogs(){$('#logs').innerHTML=state.logs.slice(0,8).map(l=>`<div class="log"><div><b>${l.subject}</b><small>${l.date} · ${l.mins} 分钟 ${l.score!==''?`· ${l.score} 分`:''}</small></div><span>${l.note||''}</span></div>`).join('')||'<div class="success">还没有学习记录。</div>'}
$('#logForm').onsubmit=e=>{e.preventDefault();state.logs.unshift({subject:$('#subject').value,mins:+$('#mins').value,score:$('#score').value,date:new Date().toLocaleDateString('zh-CN'),note:$('#note').value.trim()});save();render();$('#saveMsg').textContent='已保存。今天的学习会进入后续分析。';e.target.reset();$('#mins').value=60;};
function renderGrades(){const scored=state.logs.filter(x=>x.score!=='').map(x=>+x.score);const avg=scored.length?Math.round(scored.reduce((a,b)=>a+b,0)/scored.length):86;$('#avg').textContent=avg;$('#gradeCards').innerHTML=[['工程管理',86,'稳住基本盘'],['计算机',Math.min(100,35+state.logs.filter(x=>/Python|C语言|数据结构|数据库|Web/.test(x.subject)).length*5),'持续补强'],['创业实践',76,'控制在20%时间']].map(a=>`<div class="courseCard"><div class="meta"><span>${a[0]}</span><span>${a[1]}分</span></div><h3 style="font-size:27px">${a[1]}<small style="font-size:11px;color:var(--muted)"> /100</small></h3><p>${a[2]}</p><div class="track"><i style="width:${a[1]}%"></i></div></div>`).join('');const nums=[64,67,70,73,76,80,83,avg];$('#chart').innerHTML=nums.map((n,i)=>`<div class="col"><div class="bar2" style="height:${n*2.0}px"><label>W${i+1}</label></div></div>`).join('')}
function renderSkills(){const py=Math.min(100,42+state.logs.filter(x=>x.subject==='Python 程序设计').reduce((a,l)=>a+Math.min(8,l.mins/30),0));const a=[['工程数学',82],['英语',78],['Python',Math.round(py)],['数据结构',18]];$('#skills').innerHTML=a.map(x=>`<div class="skill"><label><span>${x[0]}</span><b>${x[1]}</b></label><div class="track"><i style="width:${x[1]}%"></i></div></div>`).join('');$('#csPct').textContent=Math.round(py)}
function renderWrong(){$('#wrongCount').textContent=state.wrong.length;$('#wrongList').innerHTML=state.wrong.length?state.wrong.map(w=>`<div class="wrongItem"><div><b>${w.subject}</b><small>${w.q} · ${w.date}</small></div><button class="mini" onclick="masterWrong(${w.id})">已掌握</button></div>`).join(''):'<div class="success">暂无待复习错题。</div>'} window.masterWrong=id=>{state.wrong=state.wrong.filter(x=>x.id!==id);save();renderWrong();update()};$('#clearWrong').onclick=()=>{state.wrong=[];save();renderWrong();update()};
function renderProjects(){$('#projectTasks').innerHTML=state.projects.map(x=>`<div class="projectTask ${x.done?'done':''}"><button onclick="toggleProject(${x.id})"></button><span>${x.name}</span></div>`).join('')}window.toggleProject=id=>{const x=state.projects.find(x=>x.id===id);x.done=!x.done;save();renderProjects();update()};
function renderQuiz(){startQuiz('Python 程序设计',0)}function startQuiz(name,chapter){if(name!=='Python 程序设计'){go('tests');$('#quiz').innerHTML=`<div class="panelhead"><h3>${name} · 章节测试</h3></div><p style="color:var(--muted);font-size:11px">该课程测试模板已建立，后续可继续扩充题库。</p><button class="primary" onclick="alert('测试已开始')">开始测试</button>`;return}go('tests');let answers={};$('#quiz').innerHTML=`<div class="panelhead"><div><h3>Python · 第 ${chapter+1} 章测试</h3><p>基础理论 + 即时错题记录</p></div><span class="pill blue">目标 ≥ 80</span></div>${QUIZ.map((q,idx)=>`<div class="quizQuestion"><b>${idx+1}. ${q.q}</b><div class="answers">${q.a.map((a,i)=>`<button onclick="choose(${idx},${i},this)">${a}</button>`).join('')}</div><small id="why${idx}" style="color:var(--muted)"></small></div>`).join('')}<div class="assignment"><b>编程作业：</b>输入学生成绩并输出等级。完成后在学习记录中填写本次成绩。</div><button class="primary" onclick="finishQuiz()">提交本次测试</button>`;window._answers=answers;window._quiz=QUIZ}
window.choose=(qi,ai,el)=>{const q=window._quiz[qi];window._answers[qi]=ai;[...el.parentElement.children].forEach((b,i)=>b.classList.toggle('correct',i===q.ok&&i===ai));if(ai!==q.ok){el.classList.add('wrong');$('#why'+qi).textContent='✕ '+q.why;state.wrong.push({id:Date.now()+qi,subject:'Python程序设计',q:q.q,date:new Date().toLocaleDateString('zh-CN')});save();renderWrong() }else{$('#why'+qi).textContent='✓ 正确'}};
window.finishQuiz=()=>{const total=window._quiz.length,got=window._quiz.reduce((s,q,i)=>s+(window._answers[i]===q.ok?1:0),0);const score=Math.round(got/total*100);alert(`本次测试：${score} 分${score>=80?'，达标，可以进入下一章。':'，未达标，建议回到课程复习后重测。'}`);if(score>=80){state.logs.unshift({subject:'Python 程序设计',mins:20,score,date:new Date().toLocaleDateString('zh-CN'),note:'章节测试'});save();render();}};
function update(){const done=state.tasks.filter(x=>x.done).length;const pct=Math.min(95,52+done*3+Math.min(7,state.logs.length)+Math.min(5,5-state.wrong.length));$('#overall').textContent=pct+'%';$('#overallBar').style.width=pct+'%';$('#heroPct').textContent=pct+'%';$('#streak').textContent=12+state.logs.length;const mins=state.logs.reduce((s,x)=>s+x.mins,0);$('#hours').textContent=(mins/60).toFixed(1);const scored=state.logs.filter(x=>x.score!=='').map(x=>+x.score);if(scored.length)$('#avg').textContent=Math.round(scored.reduce((a,b)=>a+b,0)/scored.length);}
function render(){renderTasks();renderLogs();renderWrong();renderProjects();renderGrades();renderSkills();renderCourses(ENG,'#engGrid');renderCourses(CS,'#csGrid',true);update()}
function init(){const sub=['高等数学（一）','大学英语（一）','人工智能概论','Python 程序设计','C语言','数据结构','数据库','Web开发','创业实践'];$('#subject').innerHTML=sub.map(x=>`<option>${x}</option>`).join('');$('#date').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});render();renderQuiz();$('#aiBtn').onclick=async()=>{const out=$('#aiOut');out.textContent='正在分析最近学习数据…';try{const r=await fetch('ai_plan.php',{method:'POST'});const j=await r.json();out.textContent=j.success?j.plan:(j.message||'接口未配置');}catch(e){out.textContent='前端演示建议：\n周一 高数60min + Python60min\n周二 C语言90min + 创业访谈30min\n周三 英语30min + Python作业60min\n周四 高数错题45min + 数据结构45min\n周五 Python章节测试30min\n周六 计算机3h + 创业4h\n周日 周测 + 错题复盘 + 下周计划';}}};}
init();
