<?php
require_once __DIR__.'/config/bootstrap.php';
$user = current_user();
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LinguaX — 全球智能翻译</title><link rel="stylesheet" href="assets/css/app.css"></head><body>
<header class="top"><div class="brand">Lingua<span>X</span></div><nav><a href="#translator">翻译</a><a href="pricing.php">会员</a><?php if($user): ?><a href="account.php">我的账户</a><a href="api/auth.php?action=logout">退出</a><?php else: ?><a href="login.php">登录</a><a class="btn" href="register.php">免费体验</a><?php endif; ?></nav></header>
<div class="ad top-ad">广告位 · 728×90</div>
<main id="translator"><section class="hero"><div class="pill">全球多语言 · 商业版 V2</div><h1>让语言，跨越边界。</h1><p>快速翻译文本、语音与长内容。新用户享受 1 小时免费体验。</p></section>
<section class="translator card"><div class="bar"><select id="source"><option value="auto">自动检测</option><option value="zh">中文</option><option value="en">English</option><option value="de">Deutsch</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="fr">Français</option><option value="es">Español</option></select><button id="swap">⇄</button><select id="target"><option value="en">English</option><option value="zh">中文</option><option value="de">Deutsch</option><option value="ja">日本語</option><option value="ko">한국어</option><option value="fr">Français</option><option value="es">Español</option></select></div><div class="panes"><div><textarea id="input" maxlength="5000" placeholder="输入需要翻译的内容…"></textarea><div class="tools"><button id="voice">🎤 语音</button><span id="count">0/5000</span></div></div><div class="output"><div id="result">翻译结果将在这里显示</div><div class="tools"><button id="speak">🔊 朗读</button><button id="copy">📋 复制</button></div></div></div><button class="primary" id="translate">开始翻译</button><div id="notice" class="notice"></div></section>
<div class="ad result-ad">广告位 · 翻译结果区域</div>
<section class="features"><div><b>⚡ 快速</b><p>服务端处理，减少前端绕过限制。</p></div><div><b>🔐 安全</b><p>会员、试用与权限由服务器验证。</p></div><div><b>🌍 多语言</b><p>可配置真实翻译 API 提供商。</p></div></section></main><footer>© 2026 LinguaX · 商业版 V2</footer><script src="assets/js/app.js"></script></body></html>
